// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/contact.proto

package contact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactRequest) Reset() {
	*x = GetContactRequest{}
	mi := &file_proto_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactRequest) ProtoMessage() {}

func (x *GetContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactRequest.ProtoReflect.Descriptor instead.
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_proto_rawDescGZIP(), []int{0}
}

func (x *GetContactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nama          string                 `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
	NoHp          string                 `protobuf:"bytes,3,opt,name=noHp,proto3" json:"noHp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactResponse) Reset() {
	*x = ContactResponse{}
	mi := &file_proto_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactResponse) ProtoMessage() {}

func (x *ContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactResponse.ProtoReflect.Descriptor instead.
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_proto_rawDescGZIP(), []int{1}
}

func (x *ContactResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContactResponse) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *ContactResponse) GetNoHp() string {
	if x != nil {
		return x.NoHp
	}
	return ""
}

var File_proto_contact_proto protoreflect.FileDescriptor

const file_proto_contact_proto_rawDesc = "" +
	"\n" +
	"\x13proto/contact.proto\x12\acontact\"#\n" +
	"\x11GetContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x0fContactResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04nama\x18\x02 \x01(\tR\x04nama\x12\x12\n" +
	"\x04noHp\x18\x03 \x01(\tR\x04noHp2X\n" +
	"\x0eContactService\x12F\n" +
	"\x0eGetContactByID\x12\x1a.contact.GetContactRequest\x1a\x18.contact.ContactResponseB\x17Z\x15proto/contact;contactb\x06proto3"

var (
	file_proto_contact_proto_rawDescOnce sync.Once
	file_proto_contact_proto_rawDescData []byte
)

func file_proto_contact_proto_rawDescGZIP() []byte {
	file_proto_contact_proto_rawDescOnce.Do(func() {
		file_proto_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_contact_proto_rawDesc), len(file_proto_contact_proto_rawDesc)))
	})
	return file_proto_contact_proto_rawDescData
}

var file_proto_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_contact_proto_goTypes = []any{
	(*GetContactRequest)(nil), // 0: contact.GetContactRequest
	(*ContactResponse)(nil),   // 1: contact.ContactResponse
}
var file_proto_contact_proto_depIdxs = []int32{
	0, // 0: contact.ContactService.GetContactByID:input_type -> contact.GetContactRequest
	1, // 1: contact.ContactService.GetContactByID:output_type -> contact.ContactResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_contact_proto_init() }
func file_proto_contact_proto_init() {
	if File_proto_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_contact_proto_rawDesc), len(file_proto_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_contact_proto_goTypes,
		DependencyIndexes: file_proto_contact_proto_depIdxs,
		MessageInfos:      file_proto_contact_proto_msgTypes,
	}.Build()
	File_proto_contact_proto = out.File
	file_proto_contact_proto_goTypes = nil
	file_proto_contact_proto_depIdxs = nil
}
